#!/usr/bin/perl

use strict;
use warnings;
use Carp;

use Arepa::Config;
use Arepa::BuilderFarm;
use Arepa::Builder::Sbuild;

my $config_file = 'config.yml';

my ($command, @args) = @ARGV;
if (scalar @ARGV == 0) {
    print STDERR "arepa-admin needs a command\n";
    print STDERR "Syntax: arepa-admin <command> <args> ...\n";
    exit 1;
}

if ($command eq 'createbuilder') {
    my ($builder_dir, $mirror, $distribution) = @args;
    if (scalar @args != 3) {
        print STDERR "createbuilder needs exactly three arguments\n";
        print STDERR "Syntax: arepa-admin createbuilder <schroot_dir> <debian_mirror> <distribution>\n";
        exit 1;
    }
    Arepa::Builder::Sbuild->create($builder_dir, $mirror, $distribution);
}
elsif ($command eq 'init') {
    my ($builder_dir) = @args;
    Arepa::BuilderFarm->new($config_file)->init_builders;
}
else {
    print STDERR "Unknown command '$command'\n";
    exit 1;
}
